import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

def generate_pdf_report(report_title, period_name, user_name, summary_text, structured_data=None, output_dir="reports"):
    """
    Generates a professional business intelligence report using ReportLab.
    
    :param report_title: Title of the report (e.g. "June 2026 Report")
    :param period_name: Date range / Period string (e.g. "01/06/2026 - 30/06/2026")
    :param user_name: Name of the creator
    :param summary_text: Polished executive summary / recommendation text (generated by LLM)
    :param structured_data: Optional dict or list of dicts for tables (e.g. GST divisions, vendor tables)
    :param output_dir: Directory where reports are stored
    :return: (pdf_filename, absolute_path)
    """
    os.makedirs(output_dir, exist_ok=True)
    
    # Generate unique filename using timestamp
    safe_title = "".join(x for x in report_title if x.isalnum() or x in " -_").strip().replace(" ", "_")
    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    filename = f"report_{safe_title}_{timestamp}.pdf"
    file_path = os.path.join(output_dir, filename)
    
    # Document setup
    doc = SimpleDocTemplate(
        file_path, 
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )
    
    styles = getSampleStyleSheet()
    
    # Custom colors
    primary_color = colors.HexColor("#0D9488")  # Emerald/Teal primary
    dark_neutral = colors.HexColor("#0F172A")   # Deep Slate text
    light_bg = colors.HexColor("#F8FAFC")       # Off-white panel bg
    border_color = colors.HexColor("#E2E8F0")   # Soft border
    
    # Custom styles to avoid modifying default styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=primary_color,
        spaceAfter=15
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=dark_neutral,
        spaceAfter=4
    )
    
    meta_label_style = ParagraphStyle(
        'MetaLabel',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#475569")
    )
    
    meta_val_style = ParagraphStyle(
        'MetaVal',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=12,
        textColor=dark_neutral
    )
    
    section_heading = ParagraphStyle(
        'SectionHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=13,
        leading=17,
        textColor=primary_color,
        spaceBefore=14,
        spaceAfter=8,
        keepWithNext=True
    )
    
    body_style = ParagraphStyle(
        'ReportBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=dark_neutral,
        spaceAfter=10
    )
    
    table_cell_style = ParagraphStyle(
        'TableCell',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=12,
        textColor=dark_neutral
    )
    
    table_header_style = ParagraphStyle(
        'TableHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        leading=12,
        textColor=colors.white
    )
    
    story = []
    
    # Header Section
    story.append(Paragraph("InvoiceAI Intelligence Report", title_style))
    story.append(Paragraph(f"Analysis & Business Summary: {report_title}", subtitle_style))
    story.append(Spacer(1, 10))
    
    # Metadata Grid (Table)
    metadata_data = [
        [
            Paragraph("Generated Date:", meta_label_style),
            Paragraph(datetime.utcnow().strftime("%d-%b-%Y %H:%M UTC"), meta_val_style),
            Paragraph("Reporting Period:", meta_label_style),
            Paragraph(period_name, meta_val_style),
        ],
        [
            Paragraph("Generated By:", meta_label_style),
            Paragraph(user_name, meta_val_style),
            Paragraph("Status:", meta_label_style),
            Paragraph("Official Release", meta_val_style),
        ]
    ]
    
    meta_table = Table(metadata_data, colWidths=[100, 170, 100, 170])
    meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), light_bg),
        ('BOX', (0,0), (-1,-1), 1, border_color),
        ('INNERGRID', (0,0), (-1,-1), 0.5, border_color),
        ('PADDING', (0,0), (-1,-1), 8),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 15))
    
    # Executive Summary Section
    story.append(Paragraph("Executive Summary & Recommendations", section_heading))
    # Standardize LLM output text formatting (handle double newlines)
    summary_text = summary_text.replace("\n\n", "<br/><br/>").replace("\n", "<br/>")
    story.append(Paragraph(summary_text, body_style))
    story.append(Spacer(1, 10))
    
    # Optional Structured Data Tables
    if structured_data:
        # Check if structured_data is a dict or list of dicts/tuples
        # We'll support key-value pairs (like GST totals or general lists)
        story.append(Paragraph("Structured Financial Analytics", section_heading))
        
        table_rows = []
        # Header Row
        table_rows.append([
            Paragraph("Category/Item", table_header_style), 
            Paragraph("Details/Value", table_header_style)
        ])
        
        if isinstance(structured_data, dict):
            for key, val in structured_data.items():
                # Formats
                label = str(key).replace("_", " ").title()
                if isinstance(val, (int, float)):
                    value_str = f"INR {val:,.2f}"
                else:
                    value_str = str(val)
                table_rows.append([
                    Paragraph(label, table_cell_style), 
                    Paragraph(value_str, table_cell_style)
                ])
        elif isinstance(structured_data, list):
            for item in structured_data:
                if isinstance(item, dict):
                    # Try to match name/value keys
                    keys = list(item.keys())
                    if len(keys) >= 2:
                        label = str(item[keys[0]])
                        val = item[keys[1]]
                        if isinstance(val, (int, float)):
                            value_str = f"INR {val:,.2f}"
                        else:
                            value_str = str(val)
                        table_rows.append([
                            Paragraph(label, table_cell_style), 
                            Paragraph(value_str, table_cell_style)
                        ])
                elif isinstance(item, (list, tuple)) and len(item) >= 2:
                    label = str(item[0])
                    val = item[1]
                    if isinstance(val, (int, float)):
                        value_str = f"INR {val:,.2f}"
                    else:
                        value_str = str(val)
                    table_rows.append([
                        Paragraph(label, table_cell_style), 
                        Paragraph(value_str, table_cell_style)
                    ])
                    
        if len(table_rows) > 1:
            data_table = Table(table_rows, colWidths=[270, 270])
            data_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), primary_color),
                ('ALIGN', (0,0), (-1,-1), 'LEFT'),
                ('BOTTOMPADDING', (0,0), (-1,0), 6),
                ('TOPPADDING', (0,0), (-1,0), 6),
                ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, light_bg]),
                ('BOX', (0,0), (-1,-1), 1, border_color),
                ('INNERGRID', (0,0), (-1,-1), 0.5, border_color),
                ('PADDING', (0,0), (-1,-1), 6),
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ]))
            story.append(data_table)
            
    # Build Document
    doc.build(story)
    
    return filename, os.path.abspath(file_path)
